# This is a basic workflow to help you get started with Actions

name: basic workflow check

# Controls when the workflow will run
on:
  #Triggers the workflow on push or pull request events but only for the "main" branch
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    jobs1:
         name: Run a one-line script
         runs-on: ubuntu-latest
         steps:
            - name: Step one
              run: echo Hello, world!
    
    jobs2:
         needs: [jobs1]
         name: Run a new-line script
         runs-on: ubuntu-latest
         steps:
            - name: Step second
              run: echo Hello, Mars!
