name: Run Python Script on HTML Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**/*.html'  # triggers only if HTML files are pushed

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # or specify a version like '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python Test_data_extraction.py
